### ISSUE TITLE
Integration with other build tools

### ISSUE THREAD

**Issue by toddgeist** [carafe-fm/carafe-bundle-create#1]
Looks pretty cool :-)

Many of our widgets are react based, or have some other kind of bundler, or build process that does transpilation,  tree shaking, minifying and possibly inlining.  I can't quite see how I could use this package to bootstrap that process.

How would I go about doing that?

**Comment by jeremiahsmall** [comment]
You'd want to look at the core bundler project. This is just the initializer. https://github.com/carafe-fm/carafe-bundler

**Comment by jeremiahsmall** [comment]
Actually, if you're talking about bundle-specific build process, maybe I was too hasty in pointing over there. The initializer only bootstraps a project structure so that a bundle's sources are split out in a useful way. You should be able to update the package.json file to support any additional build process before the bundling happens, so long as *that* process ends with the expected files in the `src/` directory:

- config.json
- data.json
- meta.json
- preview.jpg
- template.carafe

As long as you build out those files, either through manual editing, or some other tooling, you can then take advantage of the validator, bundler, etc.

**Comment by jeremiahsmall** [comment]
Also, the path and names of the source files are configurable if you need to change them. This is the default package.json

```json
{
  "private": true,
  "name": "carafe-bundle-template",
  "version": "0.0.0",
  "scripts": {
    "validate": "validate-carafe-bundle -b ",
    "import": "extract-carafe-bundle -b ",
    "watch": "render-carafe-source",
    "watch-port": "render-carafe-source -p ",
    "build": "compile-carafe-bundle",
    "push": "compile-carafe-bundle -f"
  },
  "devDependencies": {
    "@carafe-fm/bundler": "^1.0.0"
  },
  "carafe": {
    "templateFilename": "src/template.carafe",
    "configFilename": "src/config.json",
    "dataFilename": "src/data.json",
    "metaFilename": "src/meta.json",
    "previewFilename": "src/preview.jpg"
  }
}
```

So obviously you can configure the bundle source files to be named whatever you like at the end of your build process.

**Comment by jeremiahsmall** [comment]
Another way of thinking about it is for existing bundle projects, you don't need the initializer. You can just add the elements from the package.json file above as needed, and incorporate the bundler into an existing project.

**Comment by toddgeist** [comment]
why do I need a template.carafe?  What does that do for me?

**Comment by toddgeist** [comment]
is "template.carafe" just your "index.html" loader?

**Comment by jeremiahsmall** [comment]
> is "template.carafe" just your "index.html" loader?

Right, the reason we didn't use the `.html` suffix is that it's not valid html yet. It's a template with the bookended merge fields in it. Obviously the bundler could be configured with `"templateFilename": "src/template.html",` or any file extension and I'm certainly open to the idea of changing the default. We took the idea of using a new file extension from other templating systems. See examples from other templating systems such as `.twig`, `.latte`, `.mustache`, `.phtml`, `.tpl`, etc.

Along these same lines, in the next version of the schema, we might want to consider changing the `html` property name to `template` or something.

NB: Stating the obvious, perhaps, but (dare I say?) all editors allow configuration of file association. For example, VSCode:

```json
{
  "files.associations": {
    "*.carafe": "html"
  }
}
```

When we open a bundle for editing in CodeSandbox from within Carafe.fmp12 we push up that config so that the template file gets proper syntax highlighting, code completion, etc. See `.vscode/settings.json` in this or any example that is opened from Carafe.fmp12: https://codesandbox.io/s/43v694lno4

**Comment by toddgeist** [comment]
I  would probably not use the template as a template.  I probably would just use WebPack, and the template options it has.  I could build to that file I suppose.  

Speaking of webpack, Is there a reason you built your own WebPack Dev Server?  It feels like I can do everything I need with WebPack, WebPack Dev Server and some plugins?

**Comment by toddgeist** [comment]
I think I see why you wanted something other than WebPack.  Webpack works ok, but you'd need to restart the server every time just to compile data and config into the HTML.

**Comment by jeremiahsmall** [comment]
Yeah, we actually started with Webpack, but it made the whole thing way more complicated. It put us in a similar place to where we got with the Docker build environment.

Take a look how simple the actual server is. https://github.com/carafe-fm/carafe-bundler/blob/master/src/dev-server.js

**Comment by jeremiahsmall** [comment]
BTW, the other place custom compiled code can go is into the config, if you want to keep the template clean. E.g.

```json
{
    "$schema" : "https://carafe.fm/schema/draft-01/config.schema.json#",
    "myReactPackage": {
        "category": "Local JavaScript Packages",
        "help": "Custom React package that is generated by Webpack.",
        "isData": false,
        "label": "My React Package",
        "type": "JS Snippet",
        "value": "<theMinifiedJs>"
    }
}
```

**Comment by toddgeist** [comment]
so how do you deal with transpilation, or other bundling options?

**Comment by toddgeist** [comment]
ok I get it now....    I can make it work by using webpack to watch my code, transpile it to the temlate.carafe and the carafe dev server takes over from there.
